#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

function warning {
  echo $(tput setaf 1)$(tput bold)WARNING:$(tput sgr0)$(tput setaf 3) "$1"
  echo $(tput sgr0)
}

function changed {
  git diff --name-only HEAD@{2} HEAD | grep "^$1" >/dev/null 2>&1
}

if changed 'pnpm-lock.yaml'; then
  warning "pnpm-lock.yaml has changed, running 'pnpm install'..."
  pnpm install --frozen-lockfile
fi

exit 0
