#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

function warning {
  echo $(tput setaf 1)$(tput bold)WARNING:$(tput sgr0)$(tput setaf 3) $1
  echo $(tput sgr0)
}

function changed {
  git diff --name-only HEAD@{2} HEAD | grep "^$1" >/dev/null 2>&1
}

if changed 'yarn.lock'; then
  warning "yarn.lock has changed, running 'yarn'..."
  yarn --frozen-lockfile
fi

exit 0
